### PR TITLE
Feature/improve recordstatusdashboard performance

### PR DESCRIPTION
**Pull request by ChemiKyle**
Introduces [jQuery selector optimizations](https://learn.jquery.com/performance/optimize-selectors/) and [replaces `$.each` with a for loop](https://stackoverflow.com/questions/11887450/each-vs-for-loop-and-performance).

Other changes to the iteration over `$links`/`links` could be made but my small, uncomplicated data set makes testing difficult.

### CODE REVIEW

**Comment by pbchase** [comment]
I tried commit e05d50c in warrior-prod and there was no improvement.

**Comment by ChemiKyle** [comment]
I'll work on getting the project into the dev environment so I can benchmark all the other options.

In the meantime could you share the Developer Tools log of navigating to the Record Status Dashboard? I'm wondering if the time scaling may be dependent on the php page, and not the javascript running. It's been consistently \~52 ms for me in dev.

Screen Shot 2019-07-30 at 2 37 24 PM

**Comment by ChemiKyle** [comment]
Changes made in commit 19a2220 make `frsl.js` perform roughly 20% faster (in Firefox, clocked with `performance.now()`), a further optimization can be made to the substring collection of query parameters by not overwriting the `queryString` variable (I mistakenly thought a shorter char array would make `substr` faster).

Efficiency increases seem to scale with the number of rows, but the algorithm is still O(n) wrt links on the page. Using the information in `formsAccessMatrix` to preselect which links to alter seems like a decent avenue to pursue but may require a large refactor.

**Comment by ChemiKyle** [comment]
Using a css file and adding a class to alter the buttons instead of `disableForm(this)` seems to work on Record Status Dashboard but does _not_ work on the sidebar links while editing a record. May be due to only the first link (the button image) receiving the class and not the text.

**Comment by ChemiKyle** [comment]
The performance improvements introduced in this PR are negligible, the slowness once the page is delivered is mostly caused by the REDCap core code that builds the table. I am closing this PR.

**Pull request closed without merging**
